import "./globals.css";

import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";

import Providers from "#lib/providers/Providers.jsx";
import Header from "#ui/Header/Header.jsx";

const nanumGoth = Nanum_Gothic({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={nanumGoth.className}>
        <Providers>
          <main className="flex min-h-screen w-screen max-w-full flex-col items-center pb-28 pt-14">
            {children}
          </main>
          <Header />
        </Providers>
      </body>
    </html>
  );
}
