import "./globals.css";

import { PlatformStoreProvider } from "@lib/providers/PlatformStoreProvider";
import Header from "@ui/Header";
import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";

const nanumGoth = Nanum_Gothic({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={nanumGoth.className}>
        <PlatformStoreProvider>
          {children}
          <Header />
        </PlatformStoreProvider>
      </body>
    </html>
  );
}
